framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    templating:
        engines:
            - twig
    translator:
        enabled: true
    validation:
        enabled: true
    php_errors:
        log: true