old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            lazy: true
    producers:
        direct_campaigns:
            connection: default
            exchange_options: { name: '%rabbitmq_manager.direct_campaigns_exchange_name%', type: direct, durable: true, auto_delete: false }
        group_campaigns:
            connection: default
            exchange_options: { name: '%rabbitmq_manager.group_campaigns_exchange_name%', type: direct, durable: true, auto_delete: false }
    rpc_servers:
        registration:
            connection: default
            callback: App\EventListener\NewRecipientListener
            exchange_options: { name: '%rabbitmq_manager.recipient_registration_exchange_name%', type: direct }
            queue_options: { name: '%rabbitmq_manager.recipient_registration_queue_name%', durable: true, auto_delete: false }
            serializer: json_encode