security:
    providers:
        main:
            entity:
                class: App\Entity\Administrator
                property: username
    encoders:
        App\Entity\Administrator:
            algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            user_checker: App\Security\AdministratorChecker
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: homepage
            logout:
                path: /logout
                target: /login
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }