services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }