administrators_index:
    path: /
    controller: App\Controller\AdministratorsController::indexAction

administrators_new:
    path: /new
    controller: App\Controller\AdministratorsController::newAction

administrators_remove:
    path: /remove/{id}
    controller: App\Conroller\AdministratorsController::removeAction
    requirements:
        id: '\d+'

administrators_show:
    path: /show/{id}
    controller: App\Controller\AdministratorsController::showAction
    requirements:
        id: '\d+'

administrators_show_logs:
    path: /logs
    controller: App\Controller\AdministratorsController::showConnectionLogsAction