administrators_index:
    path: /
    controller: App\Controller\AdministratorsController::indexAction

administrators_new:
    path: /new
    controller: App\Controller\AdministratorsController::newAction

administrators_toggle_status:
    path: /toggle/{id}
    controller: App\Controller\AdministratorsController::toggleStatusAction
    requirements:
        id: \d+

administrators_show:
    path: /show/{id}
    controller: App\Controller\AdministratorsController::showAction
    requirements:
        id: \d+

administrators_show_logs:
    path: /logs/{administratorId}
    controller: App\Controller\AdministratorsController::showConnectionLogsAction
    requirements:
        userId: \d+
    defaults:
        administratorId: null
