campaings_index:
    path: /
    controller: App\Controller\CampaignsController::indexAction

campaigns_new:
    path: /new
    controller: App\Controller\CampaignsController::newAction

campaigns_modify:
    path: /modify/{id}
    controller: App\Controller\CampaignsController::modifyAction
    requirements:
        id: \d+

campaigns_remove:
    path: /remove/{id}
    controller: App\Controller\CampaignsController::removeAction
    requirements:
        id: \d+

campaigns_duplicate:
    path: /duplicate/{id}
    controller: App\Controller\CampaignsController::duplicateAction
    requirements:
        id: \d+

campaigns_show:
    path: /show/{id}
    controller: App\Controller\CampaignsController::showAction
    requirements:
        id: \d+
