recipient_groups_index:
    path: /
    controller: App\Controller\RecipientGroupsController::indexAction

recipient_groups_new:
    path: /new
    controller: App\Controller\RecipientGroupsController::newAction

recipient_groups_modify:
    path: /modify/{id}
    controller: App\Controller\RecipientGroupsController::modifyAction
    requirements:
        id: \d+

recipient_groups_remove:
    path: /remove/{id}
    controller: App\Controller\RecipientGroupsController::removeAction
    requirements:
        id: \d+

recipient_groups_show:
    path: /show/{id}
    controller: App\Controller\RecipientGroupsController::showAction
    requirements:
        id: \d+