login:
    path: /login
    controller: App\Controller\SecurityController::loginAction

login_check:
    path: /login_check
    controller: App\Controller\SecurityController::loginCheckAction

logout:
    path: /logout
    controller: App\Controller\SecurityController::logoutAction