home:
    resource: routes/home.yaml

security:
    resource: routes/security.yaml

administrators:
    resource: routes/administrators.yaml
    prefix: /administrators

campaigns:
    resource: routes/campaigns.yaml
    prefix: /campaigns

recipients:
    resource: routes/recipients.yaml
    prefix: /recipients

recipientGroups:
    resource: routes/recipient-groups.yaml
    prefix: /recipient-groups
