parameters:
    christopheranciauxgithublink: 'https://github.com/Chrisp1tv'
    alexandreszymuragithublink: 'https://github.com/alexrclens59'
    locale: 'fr'
    paginator.items_per_page: 25

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\EventListener\UserListener:
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
    App\Twig\Extension\PaginatorExtension:
        tags:
            - { name: twig.extension }