parameters:
    christopheranciauxgithublink: 'https://github.com/Chrisp1tv'
    alexandreszymuragithublink: 'https://github.com/alexrclens59'
    locale: 'fr'
    paginator.items_per_page: 25
    rabbitmq_manager.direct_campaigns_exchange_name: 'direct_campaigns_exchange'
    rabbitmq_manager.group_campaigns_exchange_name: 'group_campaigns_exchange'
    rabbitmq_manager.recipient_registration_exchange_name: 'registration_exchange'
    rabbitmq_manager.recipient_registration_queue_name: 'registration_queue'
    rabbitmq_manager.client_queues_prefix: 'client-'
    rabbitmq_manager.group_exchange_binds_prefix: 'group-'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\EventListener\UserListener:
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
    App\EventListener\NewRecipientListener:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@old_sound_rabbit_mq.direct_campaigns_producer"
            - "%rabbitmq_manager.client_queues_prefix%"
            - "%rabbitmq_manager.direct_campaigns_exchange_name%"
    App\Command\CreateUser:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.user_password_encoder.generic"
            - "@validator"
        tags:
            - { name: console.command }
    App\Command\SendPendingCampaigns:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@old_sound_rabbit_mq.direct_campaigns_producer"
            - "@old_sound_rabbit_mq.group_campaigns_producer"
            - "%rabbitmq_manager.client_queues_prefix%"
            - "%rabbitmq_manager.group_exchange_binds_prefix%"
        tags:
            - { name: console.command }
    App\Twig\Extension\PaginatorExtension:
        tags:
            - { name: twig.extension }