App\Entity\Administrator:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 62
        roles:
            type: simple_array