App\Entity\Campaign:
    type: entity
    repositoryClass: App\Repository\CampaignRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        sendingDate:
            type: datetime
            column: sending_date
        effectiveSendingDate:
            type: datetime
            column: effective_sending_date
            nullable: true
    oneToOne:
        message:
            targetEntity: App\Entity\Message
            inversedBy: campaign
            cascade:
                - "persist"
            joinColumn:
                nullable: false
    manyToOne:
        sender:
            targetEntity: App\Entity\Administrator
    manyToMany:
        recipients:
            targetEntity: App\Entity\Recipient
            joinTable:
                name: campaigns_recipients
        recipientGroups:
            targetEntity: App\Entity\RecipientGroup
            joinTable:
                name: campaigns_recipient_groups
        receivedBy:
            targetEntity: App\Entity\Recipient
            joinTable:
                name: campaigns_received_by
        seenBy:
            targetEntity: App\Entity\Recipient
            joinTable:
                name: campaings_seen_by