App\Entity\Message:
    type: entity
    repositoryClass: App\Repository\MessageRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        content:
            type: text
        color:
            type: string
        bold:
            type: boolean