App\Entity\Message:
    type: entity
    repositoryClass: App\Repository\MessageRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        content:
            type: text
        color:
            type: string
        bold:
            type: boolean
        endDate:
            type: datetime
            column: end_date
            nullable: true
        repetitionFrequency:
            type: integer
            column: repetition_frequency
            nullable: true
    oneToOne:
        campaign:
            targetEntity: App\Entity\Campaign
            mappedBy: message
