App\Entity\RecipientGroup:
    type: entity
    repositoryClass: App\Repository\RecipientGroupRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
    manyToMany:
        recipients:
            targetEntity: App\Entity\Recipient
            joinTable:
                name: recipient_groups_recipients