App\Entity\RecipientGroup:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
    manyToMany:
        recipients:
            targetEntity: App\Entity\Recipient