App\Entity\Recipient:
    type: entity
    repositoryClass: App\Repository\RecipientRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        linkingIdentifier:
            type: string
            column: linking_identifier